include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_relative_imports: warning

linter:
  rules:
    # Imports
    prefer_relative_imports: true
    avoid_relative_lib_imports: false
