name: shiftion
description: "Effortless shift management for teams."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  floor: ^1.4.0
  sqflite: ^2.3.0
  path_provider: ^2.0.0
  path: ^1.8.0
  get_it: ^8.0.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.4.0
  build_runner: ^2.4.6

scripts:
  gen: dart run build_runner build --delete-conflicting-outputs
  gen_lang: flutter gen-l10n
  build_windows: flutter build windows --release -t lib/main.dart

flutter:
  uses-material-design: true
  generate: true

assets:
  - lib/l10n/
